# Generated by Django 5.1.1 on 2026-02-18 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_color_department_size_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(max_length=10)),
                ('product_image', models.ImageField(upload_to='image')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='myapp.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
