# Generated by Django 5.1.1 on 2026-02-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_new_product_delete_color_delete_product_delete_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Product',
            new_name='Product',
        ),
    ]
