# Generated by Django 5.1.1 on 2026-02-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sale_alter_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
