# Generated by Django 5.1.1 on 2026-02-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='app_user',
            name='user_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='user_mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
