# Generated by Django 5.1.1 on 2026-02-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_app_user_profile_image_app_user_user_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_user',
            old_name='user_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='app_user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='app_user',
            old_name='user_pass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='app_user',
            old_name='user_number',
            new_name='phoneno',
        ),
    ]
