# Generated by Django 5.1.1 on 2026-03-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('discount', models.IntegerField(help_text='Discount percentage')),
                ('active', models.BooleanField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('min_amt', models.IntegerField()),
            ],
        ),
    ]
